baseURL = "https://tenfifteen.ca/"
languageCode = "en-us"
title = "Ten Fifteen Solutions"
copyright = "Copyright © 2013 - 2025 Ten Fifteen Solutions. All rights reserved."
theme = "hugo-hero-theme"

[module]
    [module.hugoVersion]
        extended = true
        min = "0.92.0"
    
[params]
    [params.logo]
        mobile = "logos/ten-fifteen-solutions.png"
        desktop = "logos/ten-fifteen-solutions.png"
        alt = "Ten Fifteen Solutions"

    [params.homepage_meta_tags]
        meta_description = "Ten Fifteen Solutions is an IT Services company based out of Toronto."
        meta_og_title = "Ten Fifteen Solutions"
        meta_og_type = "website"
        meta_og_url = "https://hugo-hero.netlify.app"
        meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
        meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[[menu.main]]
    name = "mjcb.ca"
    url = "https://mjcb.ca/"
    weight = 4

[permalinks]
    post = "/:year/:month/:day/:slug/"
    pages = "/:filename/"
